In [1]:
import numpy as np

In [5]:
a=np.arange(12).reshape(4,3)

In [6]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
b= np.arange(12,24).reshape(4,3)

In [9]:
b

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [10]:
a+b

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [14]:
b%a

/home/sunil/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 2],
       [0, 5, 4],
       [3, 2, 1]])

In [25]:
b[:,0:2]

array([[12, 13],
       [15, 16],
       [18, 19],
       [21, 22]])

In [28]:
c=b>16

In [29]:
c

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [30]:
d=b

In [31]:
d

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [39]:
d[c]=range(7)

In [40]:
d

array([[12, 13, 14],
       [15, 16,  0],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [42]:
d[c]

array([0, 1, 2, 3, 4, 5, 6])

In [44]:
c.dtype

dtype('bool')

In [50]:
c[0][1].itemsize

1

In [60]:
np.array(d,'float64')

array([[12., 13., 14.],
       [15., 16.,  0.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [61]:
d[0][1].itemsize

8

In [64]:
np.vstack((b,a))

array([[12, 13, 14],
       [15, 16,  0],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [66]:
g=np.hstack((a,b))

In [67]:
g

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16,  0],
       [ 6,  7,  8,  1,  2,  3],
       [ 9, 10, 11,  4,  5,  6]])

np.hsplit(g,6)

In [71]:
np.hsplit(g,6)

[array([[0],
        [3],
        [6],
        [9]]), array([[ 1],
        [ 4],
        [ 7],
        [10]]), array([[ 2],
        [ 5],
        [ 8],
        [11]]), array([[12],
        [15],
        [ 1],
        [ 4]]), array([[13],
        [16],
        [ 2],
        [ 5]]), array([[14],
        [ 0],
        [ 3],
        [ 6]])]

In [77]:
np.vsplit(g,2)[0]

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16,  0]])

In [78]:
g

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16,  0],
       [ 6,  7,  8,  1,  2,  3],
       [ 9, 10, 11,  4,  5,  6]])

In [79]:
g.astype('float64')

array([[ 0.,  1.,  2., 12., 13., 14.],
       [ 3.,  4.,  5., 15., 16.,  0.],
       [ 6.,  7.,  8.,  1.,  2.,  3.],
       [ 9., 10., 11.,  4.,  5.,  6.]])

In [81]:
g[0][0].itemsize

8

In [82]:
g.astype('str')

array([['0', '1', '2', '12', '13', '14'],
       ['3', '4', '5', '15', '16', '0'],
       ['6', '7', '8', '1', '2', '3'],
       ['9', '10', '11', '4', '5', '6']], dtype='<U21')

In [85]:
g.itemsize

8

In [86]:
h=g.astype('int32')

In [87]:
h.itemsize

4

In [110]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [113]:
k=np.nditer(a,order='A')

In [114]:
for i in k:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
